### PR TITLE
remove abstract *Test source file after renaming to *TestCase

### PR DESCRIPTION
**Pull request by arderyp**
https://github.com/rectorphp/rector/issues/7767

https://github.com/rectorphp/rector/issues/7767#issuecomment-1424577054

### CODE REVIEW

**Comment by arderyp** [comment]
I am not sure if new test coverage is needed.  I see there is a test to ensure that the new/renamed file was added, but I am not sure how these fixtures work and if an actual deletion is executed and, if so, how to test it.

**Comment by arderyp** [comment]
@samsonasik

**Review by samsonasik — APPROVED** [review]
Looks good

**Comment by samsonasik** [comment]
I verify locally and it seems working ok, @TomasVotruba I am merging it ;)

Thank you @arderyp

**Comment by arderyp** [comment]
very cool!

@samsonasik, in testing the rector set, I've noticed a deprecation/change that is not handled.  PHPUnit 10 seems to have done away with the old hooks (example `BeforeFirstTestHook`) and says we should now use the new `Event` system.  [This is not properly documented yet](https://github.com/sebastianbergmann/phpunit/issues/4676#issuecomment-1424814440), so I am not exactly sure what Rector should even do in these scenarios, but thought I should mention it to you.

Should I open a new issue for that? I may be able to work on it myself, but I am completely new to Rector, so it may be very slow progress.

**Comment by TomasVotruba** [comment]
Thanks for looking into this. 
Go for the pull-request :+1: We'll help you to improve the rule in small iterations.

**Comment by arderyp** [comment]
commenting here for when I look back later.

Here is a great write-up/overview of the new event system, which will come in handy here:

https://localheinz.com/articles/2023/02/14/extending-phpunit-with-its-new-event-system/

**Pull request merged**
