### PR TITLE
[BetterReflection 6.x] Fix assert($startLine > 0) on CreateMockToAnonymousClassRector

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm this should fix https://github.com/rectorphp/rector-phpunit/issues/169

### CODE REVIEW

**Comment by samsonasik** [comment]
**Before**

```
 vendor/bin/phpunit tests/Rector/ClassMethod/CreateMockToAnonymousClassRector/CreateMockToAnonymousClassRectorTest.php
PHPUnit 10.0.19 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.13
Configuration: /Users/samsonasik/www/rector-phpunit/phpunit.xml

F.F                                                                 3 / 3 (100%)

Time: 00:01.215, Memory: 88.50 MB

There were 2 failures:

1) Rector\PHPUnit\Tests\Rector\ClassMethod\CreateMockToAnonymousClassRector\CreateMockToAnonymousClassRectorTest::test with data set #0
assert($startLine > 0)
```

**After**

```
vendor/bin/phpunit tests/Rector/ClassMethod/CreateMockToAnonymousClassRector/CreateMockToAnonymousClassRectorTest.php
PHPUnit 10.0.19 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.13
Configuration: /Users/samsonasik/www/rector-phpunit/phpunit.xml

...                                                                 3 / 3 (100%)

Time: 00:01.215, Memory: 88.50 MB

OK (3 tests, 3 assertions)
```

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by staabm** [comment]
fix confirmed, thank you!

**Comment by staabm** [comment]
btw: wondering why it did not fail in CI... seems there is some coverage missing

**Comment by samsonasik** [comment]
that's depends on zend_assertion setting https://www.php.net/manual/en/ini.core.php#ini.zend.assertions

**Pull request merged**
