### PR TITLE
[PHPUnit] Skip AddDoesNotPerformAssertionToNonAssertingTestRector on method from MockBuilder

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6684

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba All checks have passed 🎉 , the pending workflow `Rector Expected — Waiting for status to be reported` seems unrelated.

**Comment by TomasVotruba** [comment]
Thanks!

İt seems the workflow is missing, could you complete it from other repository?

**Comment by samsonasik** [comment]
that's seems already applied at https://github.com/rectorphp/rector-phpunit/pull/24 ?

**Comment by TomasVotruba** [comment]
Yes, that was the intention :+1:

**Pull request merged**
