### PR TITLE
PreferPHPUnitSelfCallRector: Cheap checks first

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
@samsonasik any feedack? failling builds looks unrelated.

**Comment by TomasVotruba** [comment]
It's related, the coding standard is reported: 

Screenshot from 2024-03-08 14-43-20

**Comment by staabm** [comment]
ohh I see. the useful messages are hidden behind this error wall

grafik

**Comment by samsonasik** [comment]
@staabm I recall we discussed about it in old PR, not sure about clear algorithm steps vs performance. 

I will let @TomasVotruba decide ;)

**Comment by TomasVotruba** [comment]
LGTM, let's ship it :+1:  Thanks

**Pull request merged**
