### PR TITLE
[PHPUnit] Handle SomeClass::someMethod in message reference string

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #28

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by camporter** [comment]
Thanks, this seems like it would still have an issue if the exception message was just `SomeClass::someMethod` though.

Any reason `@expectedExceptionMessage` (and possibly `@expectedExceptionMessageRegExp`) can't be treated as plain strings? Perhaps there's some phpunit behavior I'm not familiar with though...

**Comment by samsonasik** [comment]
@camporter Fixed https://github.com/rectorphp/rector-phpunit/pull/29/commits/5c276a92006fc21f6944b3b048a29e4a555336f1

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
I tagged rector-phpunit 0.11.22 so it can be included in next rector release https://github.com/rectorphp/rector-phpunit/releases/tag/0.11.22

**Pull request merged**
