### PR TITLE
Removed @codeCoverageIgnore to attribute conversion

### PR DESCRIPTION
**Pull request by vudaltsov**
See https://github.com/sebastianbergmann/phpunit/issues/5513.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This change should be in a new PHPUnit 11 set

**Comment by vudaltsov** [comment]
> This change should be in a new PHPUnit 11 set

Even though it's deprecated in 10.4? Support for phpDoc annotations was never dropped, so it's sage to use them in any 10.x version.

**Comment by TomasVotruba** [comment]
Yes, as this would not be valid on PHPUnit 10.0.
We move the changes to next major/breaking release to be sure the features all work 100 % on the major.0 release

**Comment by vudaltsov** [comment]
> Yes, as this would not be valid on PHPUnit 10.0.

I disagree. In fact it **is** valid for PHPUnit `10.0`, `10.1`, `10.2` and `10.3`. So if you have "phpunit/phpunit": "10.0.0" and a class with `@codeCoverageIgnore` and without attribute, it will be ignored in coverage report. No warning will be triggered.

So it is safe to merge PR as is.

**Comment by TomasVotruba** [comment]
This our convention for all sets we use.

**Pull request closed without merging**
