### PR TITLE
[CodeQuality] Allow dynamic bool on AssertEqualsToSameRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8945

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @staabm

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by staabm** [comment]
Thanks 🙏

**Comment by TomasVotruba** [comment]
Thank you :partying_face:

**Pull request merged**
