### PR TITLE
[WIP] MigrateAtToConsecutiveExpectationsRector skips some cases

### PR DESCRIPTION
**Pull request by umpirsky**
Add fixture for https://getrector.org/demo/1ec84192-9d46-65fc-947d-9f7ed7e29daf as discussed in https://github.com/rectorphp/rector/issues/6976#issuecomment-1027831779.

### CODE REVIEW

**Comment by umpirsky** [comment]
@TomasVotruba Where is this fixture used? I didn't get tests failing, yet this file is ignored in my project by `MigrateAtToConsecutiveExpectationsRector`.

**Comment by TomasVotruba** [comment]
In `MigrateAtToConsecutiveExpectationsRectorTest` -> test() method.

What happens when you run tests locally?

**Comment by umpirsky** [comment]
I have `134` `at()` calls unhandled in my project, one more simple example https://getrector.org/demo/1ec842e8-d4e9-63b8-a4d1-9ff50124e2a5

**Comment by umpirsky** [comment]
This works:

```php
$query
            ->expects($this->at(0))
            ->method('get')
            ->will($this->returnValue($signed));
```

This doesn't:

```
$query
            ->expects($this->at(0))
            ->method('get')
            ->with('signed')
            ->will($this->returnValue($signed));
```

**Comment by TomasVotruba** [comment]
Could you always add the fixture to the code, so we see if that is still broken in the rule?

**Comment by umpirsky** [comment]
Added in 067912ab0e01fd022bb4eab8c88f66d24de8a87d.

**Comment by TomasVotruba** [comment]
This docs wil help you with writing the fixture: https://github.com/rectorphp/rector/blob/main/docs/how_to_add_test_for_rector_rule.md#5-add-change-or-no-change-test-fixture-file

**Comment by TomasVotruba** [comment]
This docs wil help you with writing the fixture: https://github.com/rectorphp/rector/blob/main/docs/how_to_add_test_for_rector_rule.md#5-add-change-or-no-change-test-fixture-file

**Comment by umpirsky** [comment]
OK, we have a reproducer now:

```
./vendor/bin/phpunit 
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

.............................F.......F...F.....................  63 / 145 ( 43%)
............................................................... 126 / 145 ( 86%)
..................W                                             145 / 145 (100%)

Time: 00:23.948, Memory: 1.50 GB

There was 1 warning:

1) Warning
No tests found in class "Rector\PHPUnit\Tests\TestClassResolver\Source\SeeSomeClassTest".

--

There were 3 failures:

1) Rector\PHPUnit\Tests\Rector\ClassMethod\MigrateAtToConsecutiveExpectationsRector\MigrateAtToConsecutiveExpectationsRectorTest::test with data set #7 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/ignoring_with.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     public function barTest()
     {
         $query
+            ->expects($this->at(0))
             ->method('get')
             ->with('signed')
-            ->willReturnOnConsecutiveCalls($this->returnValue($signed));
+            ->will($this->returnValue($signed));
     }
 }
 ?>

/home/umpirsky/Projects/rector-phpunit/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/umpirsky/Projects/rector-phpunit/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/umpirsky/Projects/rector-phpunit/tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/MigrateAtToConsecutiveExpectationsRectorTest.php:18

2) Rector\PHPUnit\Tests\Rector\ClassMethod\MigrateAtToConsecutiveExpectationsRector\MigrateAtToConsecutiveExpectationsRectorTest::test with data set #15 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/mixing_arrays.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function barTest()
     {
-        $this->mocks[Myclass::class]->method('sasa')->willReturnOnConsecutiveCalls([
+        $this->mocks[Myclass::class]->expects($this->at(0))->method('sasa')->willReturn([
             (new Myclass(new Myclass($winner, new Myclass(2), Myclass::getStandard())))->setUser1Result(Myclass::getByCode(Myclass::WIN))
         ]);
     }
 }
-?>
+?>

/home/umpirsky/Projects/rector-phpunit/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/umpirsky/Projects/rector-phpunit/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/umpirsky/Projects/rector-phpunit/tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/MigrateAtToConsecutiveExpectationsRectorTest.php:18

3) Rector\PHPUnit\Tests\Rector\ClassMethod\MigrateAtToConsecutiveExpectationsRector\MigrateAtToConsecutiveExpectationsRectorTest::test with data set #19 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/ignoring_with_complex.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function barTest()
     {
-        $mocks[MyClass::class]->method('convert')->with(
+        $mocks[MyClass::class]->expects($this->at(0))->method('convert')->with(
             Money::EUR(100),
             new Currency('USD')
-        )->willReturnOnConsecutiveCalls(Money::USD(120));
+        )->willReturn(Money::USD(120));
     }
 }
 ?>

/home/umpirsky/Projects/rector-phpunit/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/umpirsky/Projects/rector-phpunit/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/umpirsky/Projects/rector-phpunit/tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/MigrateAtToConsecutiveExpectationsRectorTest.php:18

```

**Comment by TomasVotruba** [comment]
Thanks :+1: 

I see there is no part under `-----`. Is that correct all of them should be just skipped?

**Comment by umpirsky** [comment]
Sorry, forgot to push 4ee9925651d7fb243a78db10adaa06dd69527f7b.

**Comment by TomasVotruba** [comment]
Thanks!

I'll merge it so Github recognizes you as a contributor and automatically allows you to run CI.
Then we'll check it, what is going on

**Pull request merged**
